using AgreementsManagement.DTO.Entities;
using AgreementsManagement.Model.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AgreementsManagement.Data.Extensions
{
    public static class Seeder
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Agreement>().HasData(
                 new Agreement { Id = 1, Status = "Pending", QuoteNumber = "02776A3", AgreementName = "HP PACK AIR INC", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 3, 18), CreatedDate = new DateTime(2022, 4, 28) },
                 new Agreement { Id = 2, Status = "Pending", QuoteNumber = "00029CONM", AgreementName = "DEMO NESTLE MRO NATSU", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 6, 11), ExpirationDate = new DateTime(2021, 6, 11), CreatedDate = new DateTime(2022, 9, 5)},
                 new Agreement { Id = 3, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 21", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 5, 12), CreatedDate = new DateTime(2022, 6, 5)},
                 new Agreement { Id = 4, Status = "Published", QuoteNumber = "02776A7", AgreementName = "HP PACK AIR INC 67", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2019, 10, 12), ExpirationDate = new DateTime(2022, 3, 19), CreatedDate = new DateTime(2020, 7, 15)},
                 new Agreement { Id = 5, Status = "Published", QuoteNumber = "00029CON8", AgreementName = "DEMO NESTLE MRO NAT09", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 3, 21), ExpirationDate = new DateTime(2022, 10, 13), CreatedDate = new DateTime(2021, 12, 25)},
                 new Agreement { Id = 6, Status = "Pending", QuoteNumber = "0277CS246", AgreementName = "HP PACK AIR INC 78", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 6, 14), ExpirationDate = new DateTime(2024, 4, 22), CreatedDate = new DateTime(2022, 8, 15)},
                 new Agreement { Id = 7, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT23", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 15), ExpirationDate = new DateTime(2023, 5, 22), CreatedDate = new DateTime(2022, 10, 5)},
                 new Agreement { Id = 8, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 99", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2018, 11, 14), ExpirationDate = new DateTime(2024, 4, 30), CreatedDate = new DateTime(2022, 12, 25)},
                 new Agreement { Id = 9, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT33", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 10, 12), ExpirationDate = new DateTime(2025, 1, 1), CreatedDate = new DateTime(2021, 6, 4)},
                 new Agreement { Id = 10, Status = "Published", QuoteNumber = "0277CS422", AgreementName = "HP PACK AIR INC 86", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 1, 23), ExpirationDate = new DateTime(2024, 7, 22), CreatedDate = new DateTime(2021, 8, 25)},
                 new Agreement { Id = 11, Status = "Peding", QuoteNumber = "02776A3", AgreementName = "HP PACK AIR INC", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 3, 18), CreatedDate = new DateTime(2022, 4, 28)},
                 new Agreement { Id = 12, Status = "Invalid", QuoteNumber = "00029CONM", AgreementName = "DEMO NESTLE MRO NATSU", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 6, 11), ExpirationDate = new DateTime(2021, 6, 11), CreatedDate = new DateTime(2022, 9, 5)},
                 new Agreement { Id = 13, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 21", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 5, 12), CreatedDate = new DateTime(2022, 6, 5)},
                 new Agreement { Id = 14, Status = "Published", QuoteNumber = "02776A7", AgreementName = "HP PACK AIR INC 67", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2019, 10, 12), ExpirationDate = new DateTime(2022, 3, 19), CreatedDate = new DateTime(2020, 7, 15)},
                 new Agreement { Id = 15, Status = "Published", QuoteNumber = "00029CON8", AgreementName = "DEMO NESTLE MRO NAT09", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 3, 21), ExpirationDate = new DateTime(2022, 10, 13), CreatedDate = new DateTime(2021, 12, 25)},
                 new Agreement { Id = 16, Status = "Published", QuoteNumber = "0277CS246", AgreementName = "HP PACK AIR INC 78", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 6, 14), ExpirationDate = new DateTime(2024, 4, 22), CreatedDate = new DateTime(2022, 8, 15)},
                 new Agreement { Id = 17, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT23", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 15), ExpirationDate = new DateTime(2023, 5, 22), CreatedDate = new DateTime(2022, 10, 5)},
                 new Agreement { Id = 18, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 99", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2018, 11, 14), ExpirationDate = new DateTime(2024, 4, 30), CreatedDate = new DateTime(2022, 12, 25)},
                 new Agreement { Id = 19, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT33", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 10, 12), ExpirationDate = new DateTime(2025, 1, 1), CreatedDate = new DateTime(2021, 6, 4)},
                 new Agreement { Id = 20, Status = "Invalid", QuoteNumber = "0277CS422", AgreementName = "HP PACK AIR INC 86", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 1, 23), ExpirationDate = new DateTime(2024, 7, 22), CreatedDate = new DateTime(2021, 8, 25)},
                 new Agreement { Id = 21, Status = "Invalid", QuoteNumber = "02776A3", AgreementName = "HP PACK AIR INC", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 3, 18), CreatedDate = new DateTime(2022, 4, 28)},
                 new Agreement { Id = 22, Status = "Published", QuoteNumber = "00029CONM", AgreementName = "DEMO NESTLE MRO NATSU", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 6, 11), ExpirationDate = new DateTime(2021, 6, 11), CreatedDate = new DateTime(2022, 9, 5)},
                 new Agreement { Id = 23, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 21", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 5, 12), CreatedDate = new DateTime(2022, 6, 5)},
                 new Agreement { Id = 24, Status = "Pending", QuoteNumber = "02776A7", AgreementName = "HP PACK AIR INC 67", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2019, 10, 12), ExpirationDate = new DateTime(2022, 3, 19), CreatedDate = new DateTime(2020, 7, 15)},
                 new Agreement { Id = 25, Status = "Published", QuoteNumber = "00029CON8", AgreementName = "DEMO NESTLE MRO NAT09", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 3, 21), ExpirationDate = new DateTime(2022, 10, 13), CreatedDate = new DateTime(2021, 12, 25)},
                 new Agreement { Id = 26, Status = "Published", QuoteNumber = "0277CS246", AgreementName = "HP PACK AIR INC 78", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 6, 14), ExpirationDate = new DateTime(2024, 4, 22), CreatedDate = new DateTime(2022, 8, 15) },
                 new Agreement { Id = 27, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT23", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 15), ExpirationDate = new DateTime(2023, 5, 22), CreatedDate = new DateTime(2022, 10, 5)},
                 new Agreement { Id = 28, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 99", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2018, 11, 14), ExpirationDate = new DateTime(2024, 4, 30), CreatedDate = new DateTime(2022, 12, 25)},
                 new Agreement { Id = 29, Status = "Published", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT33", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 10, 12), ExpirationDate = new DateTime(2025, 1, 1), CreatedDate = new DateTime(2021, 6, 4) },
                 new Agreement { Id = 30, Status = "Pending", QuoteNumber = "0277CS422", AgreementName = "HP PACK AIR INC 86", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 1, 23), ExpirationDate = new DateTime(2024, 7, 22), CreatedDate = new DateTime(2021, 8, 25) },
                 new Agreement { Id = 31, Status = "Pending", QuoteNumber = "02776A3", AgreementName = "HP PACK AIR INC", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 3, 18), CreatedDate = new DateTime(2022, 4, 28) },
                 new Agreement { Id = 32, Status = "Invalid", QuoteNumber = "00029CONM", AgreementName = "DEMO NESTLE MRO NATSU", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 6, 11), ExpirationDate = new DateTime(2021, 6, 11), CreatedDate = new DateTime(2022, 9, 5)},
                 new Agreement { Id = 33, Status = "Published", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 21", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 5, 12), CreatedDate = new DateTime(2022, 6, 5)},
                 new Agreement { Id = 34, Status = "Published", QuoteNumber = "02776A7", AgreementName = "HP PACK AIR INC 67", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2019, 10, 12), ExpirationDate = new DateTime(2022, 3, 19), CreatedDate = new DateTime(2020, 7, 15)},

                 new Agreement { Id = 35, Status = "Published", QuoteNumber = "00029CON8", AgreementName = "DEMO NESTLE MRO NAT09", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 3, 21), ExpirationDate = new DateTime(2022, 10, 13), CreatedDate = new DateTime(2021, 12, 25) },
                 new Agreement { Id = 36, Status = "Pending", QuoteNumber = "0277CS246", AgreementName = "HP PACK AIR INC 78", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 6, 14), ExpirationDate = new DateTime(2024, 4, 22), CreatedDate = new DateTime(2022, 8, 15) },
                 new Agreement { Id = 37, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT23", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 15), ExpirationDate = new DateTime(2023, 5, 22), CreatedDate = new DateTime(2022, 10, 5) },
                 new Agreement { Id = 38, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 99", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2018, 11, 14), ExpirationDate = new DateTime(2024, 4, 30), CreatedDate = new DateTime(2022, 12, 25) },
                 new Agreement { Id = 39, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT33", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 10, 12), ExpirationDate = new DateTime(2025, 1, 1), CreatedDate = new DateTime(2021, 6, 4) },
                 new Agreement { Id = 40, Status = "Published", QuoteNumber = "0277CS422", AgreementName = "HP PACK AIR INC 86", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 1, 23), ExpirationDate = new DateTime(2024, 7, 22), CreatedDate = new DateTime(2021, 8, 25) },
                 new Agreement { Id = 41, Status = "Peding", QuoteNumber = "02776A3", AgreementName = "HP PACK AIR INC", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 3, 18), CreatedDate = new DateTime(2022, 4, 28) },
                 new Agreement { Id = 42, Status = "Invalid", QuoteNumber = "00029CONM", AgreementName = "DEMO NESTLE MRO NATSU", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 6, 11), ExpirationDate = new DateTime(2021, 6, 11), CreatedDate = new DateTime(2022, 9, 5) },
                 new Agreement { Id = 43, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 21", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 5, 12), CreatedDate = new DateTime(2022, 6, 5) },
                 new Agreement { Id = 44, Status = "Published", QuoteNumber = "02776A7", AgreementName = "HP PACK AIR INC 67", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2019, 10, 12), ExpirationDate = new DateTime(2022, 3, 19), CreatedDate = new DateTime(2020, 7, 15) },
                 new Agreement { Id = 45, Status = "Published", QuoteNumber = "00029CON8", AgreementName = "DEMO NESTLE MRO NAT09", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 3, 21), ExpirationDate = new DateTime(2022, 10, 13), CreatedDate = new DateTime(2021, 12, 25) },
                 new Agreement { Id = 46, Status = "Published", QuoteNumber = "0277CS246", AgreementName = "HP PACK AIR INC 78", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 6, 14), ExpirationDate = new DateTime(2024, 4, 22), CreatedDate = new DateTime(2022, 8, 15) },
                 new Agreement { Id = 47, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT23", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 15), ExpirationDate = new DateTime(2023, 5, 22), CreatedDate = new DateTime(2022, 10, 5) },
                 new Agreement { Id = 48, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 99", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2018, 11, 14), ExpirationDate = new DateTime(2024, 4, 30), CreatedDate = new DateTime(2022, 12, 25) },
                 new Agreement { Id = 49, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT33", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 10, 12), ExpirationDate = new DateTime(2025, 1, 1), CreatedDate = new DateTime(2021, 6, 4) },
                 new Agreement { Id = 50, Status = "Invalid", QuoteNumber = "0277CS422", AgreementName = "HP PACK AIR INC 86", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 1, 23), ExpirationDate = new DateTime(2024, 7, 22), CreatedDate = new DateTime(2021, 8, 25) },
                 new Agreement { Id = 51, Status = "Invalid", QuoteNumber = "02776A3", AgreementName = "HP PACK AIR INC", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 3, 18), CreatedDate = new DateTime(2022, 4, 28) },
                 new Agreement { Id = 52, Status = "Published", QuoteNumber = "00029CONM", AgreementName = "DEMO NESTLE MRO NATSU", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 6, 11), ExpirationDate = new DateTime(2021, 6, 11), CreatedDate = new DateTime(2022, 9, 5) },
                 new Agreement { Id = 53, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 21", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 5, 12), CreatedDate = new DateTime(2022, 6, 5) },
                 new Agreement { Id = 54, Status = "Pending", QuoteNumber = "02776A7", AgreementName = "HP PACK AIR INC 67", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2019, 10, 12), ExpirationDate = new DateTime(2022, 3, 19), CreatedDate = new DateTime(2020, 7, 15) },
                 new Agreement { Id = 55, Status = "Published", QuoteNumber = "00029CON8", AgreementName = "DEMO NESTLE MRO NAT09", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 3, 21), ExpirationDate = new DateTime(2022, 10, 13), CreatedDate = new DateTime(2021, 12, 25) },
                 new Agreement { Id = 56, Status = "Published", QuoteNumber = "0277CS246", AgreementName = "HP PACK AIR INC 78", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 6, 14), ExpirationDate = new DateTime(2024, 4, 22), CreatedDate = new DateTime(2022, 8, 15) },
                 new Agreement { Id = 57, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT23", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 15), ExpirationDate = new DateTime(2023, 5, 22), CreatedDate = new DateTime(2022, 10, 5) },
                 new Agreement { Id = 58, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 99", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2018, 11, 14), ExpirationDate = new DateTime(2024, 4, 30), CreatedDate = new DateTime(2022, 12, 25) },
                 new Agreement { Id = 59, Status = "Published", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT33", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 10, 12), ExpirationDate = new DateTime(2025, 1, 1), CreatedDate = new DateTime(2021, 6, 4) },

                 new Agreement { Id = 60, Status = "Published", QuoteNumber = "0277CS422", AgreementName = "HP PACK AIR INC 86", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 1, 23), ExpirationDate = new DateTime(2024, 7, 22), CreatedDate = new DateTime(2021, 8, 25) },
                 new Agreement { Id = 61, Status = "Peding", QuoteNumber = "02776A3", AgreementName = "HP PACK AIR INC", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 3, 18), CreatedDate = new DateTime(2022, 4, 28) },
                 new Agreement { Id = 62, Status = "Invalid", QuoteNumber = "00029CONM", AgreementName = "DEMO NESTLE MRO NATSU", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 6, 11), ExpirationDate = new DateTime(2021, 6, 11), CreatedDate = new DateTime(2022, 9, 5) },
                 new Agreement { Id = 63, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 21", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 5, 12), CreatedDate = new DateTime(2022, 6, 5) },
                 new Agreement { Id = 64, Status = "Published", QuoteNumber = "02776A7", AgreementName = "HP PACK AIR INC 67", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2019, 10, 12), ExpirationDate = new DateTime(2022, 3, 19), CreatedDate = new DateTime(2020, 7, 15) },
                 new Agreement { Id = 65, Status = "Published", QuoteNumber = "00029CON8", AgreementName = "DEMO NESTLE MRO NAT09", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 3, 21), ExpirationDate = new DateTime(2022, 10, 13), CreatedDate = new DateTime(2021, 12, 25) },
                 new Agreement { Id = 66, Status = "Published", QuoteNumber = "0277CS246", AgreementName = "HP PACK AIR INC 78", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 6, 14), ExpirationDate = new DateTime(2024, 4, 22), CreatedDate = new DateTime(2022, 8, 15) },
                 new Agreement { Id = 67, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT23", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 15), ExpirationDate = new DateTime(2023, 5, 22), CreatedDate = new DateTime(2022, 10, 5) },
                 new Agreement { Id = 68, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 99", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2018, 11, 14), ExpirationDate = new DateTime(2024, 4, 30), CreatedDate = new DateTime(2022, 12, 25) },
                 new Agreement { Id = 69, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT33", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 10, 12), ExpirationDate = new DateTime(2025, 1, 1), CreatedDate = new DateTime(2021, 6, 4) },
                 new Agreement { Id = 70, Status = "Invalid", QuoteNumber = "0277CS422", AgreementName = "HP PACK AIR INC 86", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 1, 23), ExpirationDate = new DateTime(2024, 7, 22), CreatedDate = new DateTime(2021, 8, 25) },
                 new Agreement { Id = 71, Status = "Invalid", QuoteNumber = "02776A3", AgreementName = "HP PACK AIR INC", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 3, 18), CreatedDate = new DateTime(2022, 4, 28) },
                 new Agreement { Id = 72, Status = "Published", QuoteNumber = "00029CONM", AgreementName = "DEMO NESTLE MRO NATSU", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 6, 11), ExpirationDate = new DateTime(2021, 6, 11), CreatedDate = new DateTime(2022, 9, 5) },
                 new Agreement { Id = 73, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 21", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 5, 12), CreatedDate = new DateTime(2022, 6, 5) },
                 new Agreement { Id = 74, Status = "Pending", QuoteNumber = "02776A7", AgreementName = "HP PACK AIR INC 67", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2019, 10, 12), ExpirationDate = new DateTime(2022, 3, 19), CreatedDate = new DateTime(2020, 7, 15) },
                 new Agreement { Id = 75, Status = "Published", QuoteNumber = "00029CON8", AgreementName = "DEMO NESTLE MRO NAT09", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 3, 21), ExpirationDate = new DateTime(2022, 10, 13), CreatedDate = new DateTime(2021, 12, 25) },
                 new Agreement { Id = 76, Status = "Published", QuoteNumber = "0277CS246", AgreementName = "HP PACK AIR INC 78", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 6, 14), ExpirationDate = new DateTime(2024, 4, 22), CreatedDate = new DateTime(2022, 8, 15) },
                 new Agreement { Id = 77, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT23", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 15), ExpirationDate = new DateTime(2023, 5, 22), CreatedDate = new DateTime(2022, 10, 5) },
                 new Agreement { Id = 78, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 99", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2018, 11, 14), ExpirationDate = new DateTime(2024, 4, 30), CreatedDate = new DateTime(2022, 12, 25) },
                 new Agreement { Id = 79, Status = "Published", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT33", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 10, 12), ExpirationDate = new DateTime(2025, 1, 1), CreatedDate = new DateTime(2021, 6, 4) },

                 new Agreement { Id = 80, Status = "Published", QuoteNumber = "0277CS422", AgreementName = "HP PACK AIR INC 86", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 1, 23), ExpirationDate = new DateTime(2024, 7, 22), CreatedDate = new DateTime(2021, 8, 25) },
                 new Agreement { Id = 81, Status = "Peding", QuoteNumber = "02776A3", AgreementName = "HP PACK AIR INC", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 3, 18), CreatedDate = new DateTime(2022, 4, 28) },
                 new Agreement { Id = 82, Status = "Invalid", QuoteNumber = "00029CONM", AgreementName = "DEMO NESTLE MRO NATSU", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 6, 11), ExpirationDate = new DateTime(2021, 6, 11), CreatedDate = new DateTime(2022, 9, 5) },
                 new Agreement { Id = 83, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 21", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 5, 12), CreatedDate = new DateTime(2022, 6, 5) },
                 new Agreement { Id = 84, Status = "Published", QuoteNumber = "02776A7", AgreementName = "HP PACK AIR INC 67", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2019, 10, 12), ExpirationDate = new DateTime(2022, 3, 19), CreatedDate = new DateTime(2020, 7, 15) },
                 new Agreement { Id = 85, Status = "Published", QuoteNumber = "00029CON8", AgreementName = "DEMO NESTLE MRO NAT09", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 3, 21), ExpirationDate = new DateTime(2022, 10, 13), CreatedDate = new DateTime(2021, 12, 25) },
                 new Agreement { Id = 86, Status = "Published", QuoteNumber = "0277CS246", AgreementName = "HP PACK AIR INC 78", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 6, 14), ExpirationDate = new DateTime(2024, 4, 22), CreatedDate = new DateTime(2022, 8, 15) },
                 new Agreement { Id = 87, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT23", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 15), ExpirationDate = new DateTime(2023, 5, 22), CreatedDate = new DateTime(2022, 10, 5) },
                 new Agreement { Id = 88, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 99", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2018, 11, 14), ExpirationDate = new DateTime(2024, 4, 30), CreatedDate = new DateTime(2022, 12, 25) },
                 new Agreement { Id = 89, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT33", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 10, 12), ExpirationDate = new DateTime(2025, 1, 1), CreatedDate = new DateTime(2021, 6, 4) },
                 new Agreement { Id = 90, Status = "Invalid", QuoteNumber = "0277CS422", AgreementName = "HP PACK AIR INC 86", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 1, 23), ExpirationDate = new DateTime(2024, 7, 22), CreatedDate = new DateTime(2021, 8, 25) },
                 new Agreement { Id = 91, Status = "Invalid", QuoteNumber = "02776A3", AgreementName = "HP PACK AIR INC", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 3, 18), CreatedDate = new DateTime(2022, 4, 28) },
                 new Agreement { Id = 92, Status = "Published", QuoteNumber = "00029CONM", AgreementName = "DEMO NESTLE MRO NATSU", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 6, 11), ExpirationDate = new DateTime(2021, 6, 11), CreatedDate = new DateTime(2022, 9, 5) },
                 new Agreement { Id = 93, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 21", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 5, 12), CreatedDate = new DateTime(2022, 6, 5) },
                 new Agreement { Id = 94, Status = "Pending", QuoteNumber = "02776A7", AgreementName = "HP PACK AIR INC 67", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2019, 10, 12), ExpirationDate = new DateTime(2022, 3, 19), CreatedDate = new DateTime(2020, 7, 15) },
                 new Agreement { Id = 95, Status = "Published", QuoteNumber = "00029CON8", AgreementName = "DEMO NESTLE MRO NAT09", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2020, 3, 21), ExpirationDate = new DateTime(2022, 10, 13), CreatedDate = new DateTime(2021, 12, 25) },
                 new Agreement { Id = 96, Status = "Published", QuoteNumber = "0277CS246", AgreementName = "HP PACK AIR INC 78", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2021, 6, 14), ExpirationDate = new DateTime(2024, 4, 22), CreatedDate = new DateTime(2022, 8, 15) },
                 new Agreement { Id = 97, Status = "Pending", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT23", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 15), ExpirationDate = new DateTime(2023, 5, 22), CreatedDate = new DateTime(2022, 10, 5) },
                 new Agreement { Id = 98, Status = "Invalid", QuoteNumber = "0277CSL26", AgreementName = "HP PACK AIR INC 99", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2018, 11, 14), ExpirationDate = new DateTime(2024, 4, 30), CreatedDate = new DateTime(2022, 12, 25) },
                 new Agreement { Id = 99, Status = "Published", QuoteNumber = "0277CSL26", AgreementName = "HP NESTLE MRO NAT33", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 10, 12), ExpirationDate = new DateTime(2025, 1, 1), CreatedDate = new DateTime(2021, 6, 4) },
                 new Agreement { Id = 100, Status = "Invalid", QuoteNumber = "02776A3", AgreementName = "HP PACK AIR INC", AgreementType = "SPA", DistributorName = "Werner", EffectiveDate = new DateTime(2022, 3, 1), ExpirationDate = new DateTime(2023, 3, 18), CreatedDate = new DateTime(2022, 4, 28) }

               );

            modelBuilder.Entity<Account>().HasData(new Account { userName = "Admin", password = "123", fullName = "Nguyen Minh Trung", email= "abc@gmail.com"}); ;
        }
    }
}
