// <auto-generated />
using System;
using AgreementsManagement.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgreementsManagement.Data.Migrations
{
    [DbContext(typeof(AgreementsManagementDbContext))]
    [Migration("20220617024729_updateDb")]
    partial class updateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AgreementsManagement.DTO.Entities.Agreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AgreementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgreementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 6, 17, 9, 47, 28, 876, DateTimeKind.Local).AddTicks(768));

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 6, 17, 9, 47, 28, 876, DateTimeKind.Local).AddTicks(510));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agreements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgreementName = "HP PACK AIR INC",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "02776A3",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            AgreementName = "DEMO NESTLE MRO NATSU",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2020, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "00029CONM",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            AgreementName = "HP PACK AIR INC 21",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Invalid"
                        },
                        new
                        {
                            Id = 4,
                            AgreementName = "HP PACK AIR INC 67",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "02776A7",
                            Status = "Published"
                        },
                        new
                        {
                            Id = 5,
                            AgreementName = "DEMO NESTLE MRO NAT09",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2020, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2022, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "00029CON8",
                            Status = "Published"
                        },
                        new
                        {
                            Id = 6,
                            AgreementName = "HP PACK AIR INC 78",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2021, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CS246",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 7,
                            AgreementName = "HP NESTLE MRO NAT23",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Invalid"
                        },
                        new
                        {
                            Id = 8,
                            AgreementName = "HP PACK AIR INC 99",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Invalid"
                        },
                        new
                        {
                            Id = 9,
                            AgreementName = "HP NESTLE MRO NAT33",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2021, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 10,
                            AgreementName = "HP PACK AIR INC 86",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2021, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CS422",
                            Status = "Published"
                        },
                        new
                        {
                            Id = 11,
                            AgreementName = "HP PACK AIR INC",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "02776A3",
                            Status = "Peding"
                        },
                        new
                        {
                            Id = 12,
                            AgreementName = "DEMO NESTLE MRO NATSU",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2020, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "00029CONM",
                            Status = "Invalid"
                        },
                        new
                        {
                            Id = 13,
                            AgreementName = "HP PACK AIR INC 21",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 14,
                            AgreementName = "HP PACK AIR INC 67",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "02776A7",
                            Status = "Published"
                        },
                        new
                        {
                            Id = 15,
                            AgreementName = "DEMO NESTLE MRO NAT09",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2020, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2022, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "00029CON8",
                            Status = "Published"
                        },
                        new
                        {
                            Id = 16,
                            AgreementName = "HP PACK AIR INC 78",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2021, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CS246",
                            Status = "Published"
                        },
                        new
                        {
                            Id = 17,
                            AgreementName = "HP NESTLE MRO NAT23",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 18,
                            AgreementName = "HP PACK AIR INC 99",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Invalid"
                        },
                        new
                        {
                            Id = 19,
                            AgreementName = "HP NESTLE MRO NAT33",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2021, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Invalid"
                        },
                        new
                        {
                            Id = 20,
                            AgreementName = "HP PACK AIR INC 86",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2021, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CS422",
                            Status = "Invalid"
                        },
                        new
                        {
                            Id = 21,
                            AgreementName = "HP PACK AIR INC",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "02776A3",
                            Status = "Invalid"
                        },
                        new
                        {
                            Id = 22,
                            AgreementName = "DEMO NESTLE MRO NATSU",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2020, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "00029CONM",
                            Status = "Published"
                        },
                        new
                        {
                            Id = 23,
                            AgreementName = "HP PACK AIR INC 21",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Invalid"
                        },
                        new
                        {
                            Id = 24,
                            AgreementName = "HP PACK AIR INC 67",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "02776A7",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 25,
                            AgreementName = "DEMO NESTLE MRO NAT09",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2020, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2022, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "00029CON8",
                            Status = "Published"
                        },
                        new
                        {
                            Id = 26,
                            AgreementName = "HP PACK AIR INC 78",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2021, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CS246",
                            Status = "Published"
                        },
                        new
                        {
                            Id = 27,
                            AgreementName = "HP NESTLE MRO NAT23",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 28,
                            AgreementName = "HP PACK AIR INC 99",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Invalid"
                        },
                        new
                        {
                            Id = 29,
                            AgreementName = "HP NESTLE MRO NAT33",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2021, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Published"
                        },
                        new
                        {
                            Id = 30,
                            AgreementName = "HP PACK AIR INC 86",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2021, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CS422",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 31,
                            AgreementName = "HP PACK AIR INC",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "02776A3",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 32,
                            AgreementName = "DEMO NESTLE MRO NATSU",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2020, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "00029CONM",
                            Status = "Invalid"
                        },
                        new
                        {
                            Id = 33,
                            AgreementName = "HP PACK AIR INC 21",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "0277CSL26",
                            Status = "Published"
                        },
                        new
                        {
                            Id = 34,
                            AgreementName = "HP PACK AIR INC 67",
                            AgreementType = "SPA",
                            CreatedDate = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributorName = "Werner",
                            EffectiveDate = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteNumber = "02776A7",
                            Status = "Published"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
